# Generated by Django 4.1 on 2022-09-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_slots_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
