export const CHANGE_LOADING = 'CHANGE_LOADING';
export const CHANGE_ERROR = 'CHANGE_ERROR';
export const CHANGE_USER = 'CHANGE_USER';
export const CHANGE_TOKEN = 'CHANGE_TOKEN';
export const CHANGE_SCHEDULES = 'CHANGE_SCHEDULES';