# Generated by Django 4.1 on 2022-09-03 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_slots_description'),
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify', to='schedule.slots')),
            ],
        ),
    ]
