# Generated by Django 4.1 on 2022-09-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='event_id',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
