# Generated by Django 4.1 on 2022-09-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_meeting_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='event_id',
            field=models.CharField(max_length=200),
        ),
    ]
