# Generated by Django 4.1 on 2022-09-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_url',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
